"""Export the recommended ruleset as iptables commands.

Assumes a Linux router/firewall with one interface per zone, filtering
inter-zone traffic on the FORWARD chain. Zone names map to the proposed
subnets assigned by the recommender. Review before applying — generated
config is a starting point, not a substitute for change control.
"""

from __future__ import annotations

from ..models import Rule, Zone


def export(zones: list[Zone], rules: list[Rule]) -> str:
    subnet = {z.name: z.subnet for z in zones}
    lines: list[str] = [
        "#!/usr/bin/env bash",
        "# Generated by segmentation-advisor — review before applying.",
        "# Inter-zone policy enforced on the FORWARD chain of a zone router.",
        "set -euo pipefail",
        "",
        "# Flush and default-deny: zero-trust posture (NIST SP 800-207 §3.1.2).",
        "iptables -F FORWARD",
        "iptables -P FORWARD DROP",
        "",
        "# Allow return traffic for established sessions.",
        "iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
        "",
    ]

    for rule in rules:
        if rule.action != "allow":
            continue  # default-deny is already the FORWARD policy
        src = subnet.get(rule.src_zone)
        dst = subnet.get(rule.dst_zone)
        if not src or not dst:
            continue
        lines.append(f"# {rule.src_zone} -> {rule.dst_zone}: {rule.justification}")
        lines.append(
            "iptables -A FORWARD"
            f" -s {src} -d {dst}"
            f" -p {rule.protocol} --dport {rule.port}"
            " -m conntrack --ctstate NEW -j ACCEPT"
        )
        lines.append("")

    lines.append("# Everything else falls through to the DROP policy.")
    return "\n".join(lines) + "\n"
