"""Export the recommended ruleset as pfSense-style rule definitions.

pfSense evaluates rules on the interface where traffic *enters* the
firewall, so rules are grouped by source-zone interface. Output is a
human-readable definition list intended to be entered via the GUI (or
adapted into a config.xml import); pfSense's implicit default on every
interface is already "block all", which matches the zero-trust posture.
"""

from __future__ import annotations

from ..models import Rule, Zone


def _iface(zone_name: str) -> str:
    return zone_name.upper().replace("-", "_")


def export(zones: list[Zone], rules: list[Rule]) -> str:
    subnet = {z.name: z.subnet for z in zones}
    by_src: dict[str, list[Rule]] = {}
    for rule in rules:
        if rule.action == "allow" and rule.src_zone in subnet:
            by_src.setdefault(rule.src_zone, []).append(rule)

    lines: list[str] = [
        "# Generated by segmentation-advisor — pfSense inter-zone policy.",
        "# Apply each block on the named interface (Firewall > Rules).",
        "# pfSense blocks all traffic not matched by a pass rule, so no",
        "# explicit default-deny entries are needed.",
        "",
    ]

    for zone in zones:
        zone_rules = by_src.get(zone.name)
        if not zone_rules:
            continue
        lines.append(f"## Interface: {_iface(zone.name)}  ({zone.subnet} — {zone.description})")
        for i, rule in enumerate(zone_rules, 1):
            dst = subnet.get(rule.dst_zone, rule.dst_zone)
            lines.append(
                f"  [{i}] pass  proto {rule.protocol}"
                f"  from {_iface(rule.src_zone)} net"
                f"  to {dst}  port {rule.port}"
            )
            lines.append(f"      description: {rule.justification}")
        lines.append("")

    lines.append("# Implicit per-interface default: block all remaining traffic.")
    return "\n".join(lines) + "\n"
